FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt ./
RUN pip install --prefix=/install -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

RUN useradd -m brendan

COPY --from=builder /install /usr/local

COPY . .

USER brendan

EXPOSE 8000

CMD ["python", "main.py"]